### ISSUE TITLE
Comparison with modern boilerplates

### ISSUE THREAD

**Issue by dandv** [fent/node-module-boilerplate#1]
https://github.com/diegohaz/nod

https://github.com/jsynowiec/node-flowtype-boilerplate

https://github.com/sheerun/modern-node

**Comment by fent** [comment]
Didn't intend this to be a widely used tool, just something I use myself. It doesn't have a cli command to create a new module, But I used to call [pkginit](https://www.npmjs.com/package/pkginit) with it.

This doesn't have any precompiling, preprocessing, prettyfying, or linting like the others linked. I do linting, but on my editor. If I ever switch to prettyfying, it would be on my editor too.

Most of the time I make these modules for just myself, other contributors can come later. Populating the  repo with many setting files feels messy.

Testing is with [mocha](https://mochajs.org/)
Code coverage with [istanbul](https://github.com/gotwarlost/istanbul) and https://coveralls.io/
No `yarn.lock` file

This doesn't have anything that helps with version bumping and publishing, that seems simple enough already.
